name: Code quality
"on": ["push"]
jobs:
  unittests:
    name: "Pytest"
    strategy:
      matrix:
        year: [2023, 2024]
        python-version: [3.11]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==1.8.3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install dependencies
        run: poetry install
        working-directory: ./solutions/year_${{ matrix.year }}

      - name: Run tests
        run: poetry run pytest
        working-directory: ./solutions/year_${{ matrix.year }}
